name: Publish Release
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'version'
        required: true
        type: string

jobs:


  build_push_x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: martabal
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for x86
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            ARCH=amd64

          tags: |
            martabal/act_runner:${{ inputs.tags }}
            martabal/act_runner:latest

  build_push_arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: martabal
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for arm64
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./
          file: ./Dockerfile.aarch64
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            ARCH=arm64
          tags: |
            martabal/act_runner:arm-${{ inputs.tags }}
            martabal/act_runner:arm-latest